name: CI (bento) arm64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on:
    - self-hosted
    - "os=linux"
    - "arch=arm64"
    # Substitute your cluster name, typically, a mineral name like
    # "pyrite", "kyanite"
    - "engflow-cluster=local"
    - "engflow-bento-name=mybento-arm64"
    - "engflow-bento-allow-save=true"

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Run presubmit checks
      run: |
        bazel test //...
