name: bazel (bento)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on:
    - self-hosted
    - "os=linux"
    - "arch=x64"
    # Substitute your cluster name, typically, a mineral name like
    # "pyrite", "kyanite"
    - "engflow-cluster=local"
    - "engflow-bento-name=mybento-x64"
    - "engflow-bento-allow-save=true"
    - "engflow-job-type=${{github.event_name}}-${{github.ref_name}}"

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Run bazel
      run: |
        bazel info
